In [ ]:
import numpy as np 
import matplotlib.pyplot as plt

In [ ]:
t = np.linspace(0,60,60)
mu = 4.*np.pi*10**(-7)
h = 52.
l = 17.
f = 60.
I_0 = 5.e4
I = I_0*np.sin(2*np.pi*f*t)
plt.plot(t, I)
mu

In [ ]:
r = np.sqrt((h**2) + ((l/2)**2))

B = (mu/(2*np.pi*r))*(2*max(I))*(l/(2*r))
B

In [ ]:
A = 2*0.5
emf = B*A*(2*np.pi*f)
emf

In [ ]:
l =1.4/8
l

In [ ]:
2.5*.175

In [ ]:
q = -8e-8
q_2 = q/8
q_2

In [ ]:
k = 9e9
r_mag = np.sqrt((0.4375)**2 + (0.7)**2)
r = np.array([0.7, -0.4375,0])
r_hat = r/r_mag
E = ((k*q_2)/r_mag**2)*r_hat
E

In [ ]:
eps = 8.85e-12
Q = 0.6e-7
alpha = 1.96e-40
L = 0.8
d = 1.4*0.01
m = 1.99e-26
k_sqd = (1/(4*np.pi*eps))**2
acc_top = k_sqd*(Q**2)*alpha
acc_bot = (L**2)*m*(d**3)
acc_top/acc_bot

In [ ]:
1/6**3

In [ ]:
k = 8.99e9
q = 5e-9
l=0.18
r = np.sqrt((l/3)**2 + (0.07)**2)

((k*q/3)*(l/3))/r**(3/2)

In [ ]:
1339.9+1339.9+3061.2

In [ ]:
A = np.pi*(16*0.01)**2
Q = 8e-6
e_0 = 8.85e-12
z = 0.02
r = 0.16

E = Q/(2*A*e_0)

E*(1 - (z/(z**2 + r**2)))

#E*(1-z/r)
E

r1=16*1/100
r1

In [ ]:
import numpy as np 

k = 8.99e9
r = np.array([0.5, 0, 0])
r_mag = np.sqrt(np.dot(r,r))
r_hat = r/r_mag
q = 5e-9

E = k*q*r_hat/r_mag**2
E

In [ ]:
q = 1.6e-19
E = 400
F = q*E
F

In [ ]:
Q=3*q
400*Q

In [ ]:
k=8.99e9
r2 = np.array([0.5, -0.2, -0.5])
q = 4.5e-9
r1 = np.array([-0.6, -0.7, -0.2])
r = r2-r1
r_mag = np.sqrt(np.dot(r,r))
r_hat = r/r_mag

E = k*q*r_hat/r_mag**2
E

In [ ]:
b = np.array([-0.1, -0.3, 0])
b_mag = np.sqrt(np.dot(b,b))
b_hat = b/b_mag
q = 1e-9
k = 8.99e9

E = k*q*b_hat/b_mag**2
E

In [ ]:
a2 = np.array([26e-2,0,0])
a1 = np.array([85e-2,0,0])
a = a2-a1
a_mag = np.sqrt(np.dot(a,a))
a_hat = r/r_mag
q = -9.5e-9
k = 8.99e9

E = k*q*a_hat/a_mag**2
E

In [10]:
import numpy as np

q = -1.6e-19
k=8.99e9
r1 = np.array([0.9, 0.7, -0.1])
r2 = np.array([0.5, 1.3, -0.5])
r = r2-r1
rmag = np.sqrt(np.dot(r,r))
rhat = r/rmag

E = k*q*rhat/rmag**2
E

array([ 1.02606836e-09, -1.53910254e-09,  1.02606836e-09])

In [17]:
k = 8.99e9
E = 4.3e6
qp = 1.6e-19
qe = -1.6e-19
Ehat = np.array([0,1,0])
rhat = -Ehat
# +x to the east, +y to the north, +z out of screen

rmag = np.sqrt(k*qp/E)
r = rhat*rmag
r

array([ 0.0000000e+00, -1.8289659e-08,  0.0000000e+00])

In [19]:
k = 8.99e9
E = 4.3e6
qp = 1.6e-19

Ehat = np.array([0,1,0])

rpmag = np.sqrt(2*k*qp/E)
rpmag

2.586548386970469e-08

In [26]:
import numpy as np 

k = 8.99e9
q1 = -2e-9
q2 = 6e-9
a1 = np.array([-0.02, 0.05, 0])
a2 = np.array([0.03, -0.03, 0])
A = np.array([-0.07, -0.07, 0])
r1 = A - a1
r2 = A - a2
r1mag = np.sqrt(np.dot(r1,r1))
r2mag = np.sqrt(np.dot(r2,r2))
r1hat = r1/r1mag
r2hat = r2/r2mag

E1 = k*q1*r1hat/r1mag**2
E2 = k*q2*r2hat/r2mag**2
E = E1 + E2
E

array([-3908.22225668,  -744.90019079,     0.        ])

In [50]:
import numpy as np

k=9e9

q1 = 1e-6
q2 = 9e-6
q3 = -4e-6

r1 = np.array([0.03, 0, 0])
r2 = np.array([0.03, 0.04, 0])
r3 = np.array([0, 0.04, 0])
r1mag = np.sqrt(np.dot(r1, r1))
r2mag = np.sqrt(np.dot(r2, r2))
r3mag = np.sqrt(np.dot(r3, r3))
r1hat = r1/r1mag
r2hat = r2/r2mag
r3hat = r3/r3mag

E1 = k*q1*r1hat/r1mag**2
E2 = k*q2*r2hat/r2mag**2
E3 = k*q3*r3hat/r3mag**2
E = E1+E2+E3

qa = 2*1.6e-19
ma = 6.646e-27
Fa = qa*E
Fa/ma

array([1.41751429e+15, 1.64670478e+14, 0.00000000e+00])

In [59]:
import numpy as np

k = 9e9
q = 4e-9
s = 0.001
d = 0.05
r = np.sqrt(d**2 + s**2)
P = q*s
Ea = k*2*P/d**3
Eb = k*P/r**3
Eb

287.827286359698

In [73]:
import numpy as np 

k = 9e9
s1 = 0.4e-3
s2 = 0.3e-3
q1 = 11e-9
q2 = 5e-9
P1 = q1*s1
P2 = q2*s2
d1 = 0.24
d2 = 0.16

E1 = k*P1/d1**3
E2 = k*2*P2/d2**3
E2-E1

3.7272135416666647

In [76]:
3.17e-7*1e9

317.0