In [1]:
import numpy as np

In [2]:
def back_sub(A, b):
    """
    Backward substitution
    The right hand side b is changed in place to store the solution
    A: the coefficient matrix of size n x n, i.e. a square matrix
    b: the right hand side of n
    """
    if A.shape[0] != A.shape[1]: # if the number of rows [0], does not equal the number of columns [1] 
        print('Error: the given coefficient matrix is not square.')  
        return 
    
    if A.shape[0] != b.size:
        print('Error: the shape of the coefficient matrix does not match the size of the RHS.')
        return
    
    n = A.shape[0]
    
    for i in range(n-1, -1, -1):
        for j in range(i+1, n):
            b[i] = b[i] - A[i,j]*b[j]
        b[i] = b[i]/A[i,i]
        
def GaussianElim(A, b):
    """
    Gaussian Elimination without pivoting. 
    The coefficient matrix A and the right hand side b are modified in place.
    Input:
    A: the coefficient matrix of size n x n
    b: the right hand side of size n    
    Return:
    None. The solution is stored in b
    """
    if A.shape[0] != A.shape[1]:
        print('Error: the given coefficient matrix is not square')
        return
    
    if A.shape[0] != b.size:
        print('Error: the shape of the coefficient matrix does not match the size of the RHS')
        return
     
    # We hard code the epsilon here. It can be an input parameter.
    eps = 1e-5 
    n = A.shape[0]

    for j in range(n-1):
        if np.abs(A[j,j]) < eps:
            print('Error: zero pivot encountered!')
            return
        for i in range(j+1, n):
            # The multiplier
            mp = A[i,j]/A[j,j]
            for k in range(j+1,n):
                A[i,k] = A[i,k] - mp*A[j,k]
            b[i] = b[i] - mp*b[j]
    
    # No need to return. Both A and b are changed in place

In [3]:
A = np.array([[2., 3, -1], [4, -2, 3], [2, -1, 2]])
b = np.array([-3, 12, 7])
print('Solve the linear system: ')
print(A, 'x = ', b)
GaussianElim(A, b)
back_sub(A, b)
print('The solution is ', b)

Solve the linear system: 
[[ 2.  3. -1.]
 [ 4. -2.  3.]
 [ 2. -1.  2.]] x =  [-3 12  7]
The solution is  [ 1 -1  2]


In [4]:
def LU(A):
    """
    LU factorization without pivoting. 
    The coefficient matrix A is modified in place.
    The lower triangular part of A represents the L matrix, the upper triangular part 
    (including the diagonal) represents U
    A: the coefficient matrix of size n x n   
    """
    if A.shape[0] != A.shape[1]:
        print('Error: the given coefficient matrix is not square')
        return   
     
    # We hard code the epsilon here. It can be an input parameter.
    eps = 1e-5 
    n = A.shape[0]

    for j in range(n-1):
        if np.abs(A[j,j]) < eps:
            print('Error: zero pivot encountered!')
            return
        for i in range(j+1, n):
            # The multiplier
            mp = A[i,j]/A[j,j]
            A[i,j] = mp
            for k in range(j+1,n):
                A[i,k] = A[i,k] - mp*A[j,k]
    
    # No need to return. A is changed in place.

In [5]:
A = np.array([[2.,3,-1], [4,-2,3], [2, -1, 2]])
print('Perform LU decomposition of A = : ')
print(A)
LU(A)
print('The result is ')
print(A)

Perform LU decomposition of A = : 
[[ 2.  3. -1.]
 [ 4. -2.  3.]
 [ 2. -1.  2.]]
The result is 
[[ 2.   3.  -1. ]
 [ 2.  -8.   5. ]
 [ 1.   0.5  0.5]]


In [6]:
def forward_sub(A, b, A_from_LU):
    """
    Forward substitution
    The right hand side b is changed in place to store the solution
    A: the coefficient matrix of size n x n
    b: the right hand side of size n
    A_from_LU: True, if the matrix A is from LU factorization (diagonals are 1).
               False, if A is just a regular coefficient matrix
    """
    if A.shape[0] != A.shape[1]:
        print('Error: the given coefficient matrix is not square')
        return
    
    if A.shape[0] != b.size:
        print('Error: the shape of the coefficient matrix does not match the size of the RHS')
        return
     
    n = A.shape[0]
    
    if A_from_LU:
        for j in range(0,n):       
            b[j+1:] = b[j+1:] - A[j+1:,j]*b[j]
    else:
        for j in range(0,n):  
            b[j] = b[j]/A[j,j]
            b[j+1:] = b[j+1:] - A[j+1:,j]*b[j]

In [7]:
def forward_sub(A, b, A_from_LU):
    """
    Forward substitution
    The right hand side b is changed in place to store the solution
    A: the coefficient matrix of size n x n
    b: the right hand side of size n
    A_from_LU: True, if the matrix A is from LU factorization (diagonals are 1).
               False, if A is just a regular coefficient matrix
    """
    if A.shape[0] != A.shape[1]:
        print('Error: the given coefficient matrix is not square')
        return
    
    if A.shape[0] != b.size:
        print('Error: the shape of the coefficient matrix does not match the size of the RHS')
        return
     
    n = A.shape[0]
    
    if A_from_LU:
        for j in range(0,n):       
            b[j+1:] = b[j+1:] - A[j+1:,j]*b[j]
    else:
        for j in range(0,n):  
            b[j] = b[j]/A[j,j]
            b[j+1:] = b[j+1:] - A[j+1:,j]*b[j]

In [8]:
A = np.array([[2.,3,-1], [4,-2,3], [2, -1, 2]])
b = np.array([-3,12,7])
# Perform LU factorization
LU(A)
print('The matrix A after LU decomposition is ')
print(A)
# Perform forward substitution
forward_sub(A,b,True)
print('After forward substition, the vector b is')
print(b)
# Perform back substitution
back_sub(A,b)
print('After backward substition, the vector b is')
print(b)

The matrix A after LU decomposition is 
[[ 2.   3.  -1. ]
 [ 2.  -8.   5. ]
 [ 1.   0.5  0.5]]
After forward substition, the vector b is
[-3 18  1]
After backward substition, the vector b is
[ 1 -1  2]


In [9]:
def GEPP(A, b):
    """
    Gaussian elimination with partial pivoting. 
    The coefficient matrix A is modified in place.
    A: the coefficient matrix of size n x n
    b: the right hand side of size n    
    Return:
    None. The solution is stored in b
    """
    if A.shape[0] != A.shape[1]:
        print('Error: the given coefficient matrix is not square')
        return  
     
    n = A.shape[0]

    for j in range(n-1):
        # find p
        p = np.argmax(np.abs(A[j:,j]))        
        if p+j != j:
            # change rows p and j of A and b:
            A[[p+j, j]] = A[[j, p+j]]
            b[[p+j, j]] = b[[j, p+j]]
        for i in range(j+1, n):
            # The multiplier
            mp = A[i,j]/A[j,j]
            A[i,j] = 0.
            b[i] = b[i] - mp*b[j]
            for k in range(j+1,n):
                A[i,k] = A[i,k] - mp*A[j,k]

In [16]:
%%time

A = np.array([[3., -2, 1], 
              [6, 1, -3], 
              [-4, 3, -2]])
b = np.array([-1., 18, 3])
print('Solve the linear system: ')
print(A, 'x = ', b)
GEPP(A, b)
print('After Gaussian elimination with partial pivoting, A becomes:')
print(A)
print('After Gaussian elimination with partial pivoting, b becomes:')
print(b)
back_sub(A, b)
print('The solution is ', b)

Solve the linear system: 
[[ 3. -2.  1.]
 [ 6.  1. -3.]
 [-4.  3. -2.]] x =  [-1. 18.  3.]
After Gaussian elimination with partial pivoting, A becomes:
[[ 6.          1.         -3.        ]
 [ 0.          3.66666667 -4.        ]
 [ 0.          0.         -0.22727273]]
After Gaussian elimination with partial pivoting, b becomes:
[18.         15.          0.22727273]
The solution is  [ 2.  3. -1.]
CPU times: total: 0 ns
Wall time: 3.24 ms


The partial pivoting algorithm leads to a new matrix factorization for A, which takes the form of 

$$ PA = LU $$

where $L$ and $U$ have the same forms as defined in $LU$ factorization, and $P$ is a permutation matrix. 

A permutation matrix is a square matis where every entry is either a $1$ or a $0$ that can be obtained by a sequence of exchanges of rows or columns of the identity matrix of the same dimension. 

$$ PAx = Pb $$

$$ LUx = Pb $$

$$ Lc = Pb $$
$$ Ux = C $$

In [11]:
def PALU(A):
    """
    PA=LU factorization with partial pivoting. 
    The coefficient matrix A is modified in place.
    The lower triangular part of A represents the L matrix, the upper triangular part 
    (including the diagonal) represents U
    A: the coefficient matrix of size n x n
    output:
    Permutation matrix $P$ is returned, along with $A$ that is changed in place
    """
    if A.shape[0] != A.shape[1]:
        print('Error: the given coefficient matrix is not square')
        return   
     
    n = A.shape[0]
    P = np.eye(n)

    for j in range(n-1):
        # find p
        p = np.argmax(np.abs(A[j:,j]))        
        if p+j != j:
            # change rows p and j of A. Update P:
            A[[p+j, j]] = A[[j, p+j]]
            P[[p+j, j]] = P[[j, p+j]]   
        for i in range(j+1, n):
            # The multiplier
            mp = A[i,j]/A[j,j]
            A[i,j] = mp
            for k in range(j+1,n):
                A[i,k] = A[i,k] - mp*A[j,k]
    return P

In [15]:
%%time

A = np.array([[3., -2, 1], [6, 1, -3], [-4, 3, -2]])
print('Perform PA=LU factorization: ')
print('Before PA=LU factorization, A = ')
print(A)

P = PALU(A)
print('The PA=LU factorization result is ')
print('After PA=LU factorization, A = ')
print(A)
print('The permutation matrix P = ')
print(P)

Perform PA=LU factorization: 
Before PA=LU factorization, A = 
[[ 3. -2.  1.]
 [ 6.  1. -3.]
 [-4.  3. -2.]]
The PA=LU factorization result is 
After PA=LU factorization, A = 
[[ 6.          1.         -3.        ]
 [-0.66666667  3.66666667 -4.        ]
 [ 0.5        -0.68181818 -0.22727273]]
The permutation matrix P = 
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
CPU times: total: 0 ns
Wall time: 6.52 ms


In [18]:
import struct
def float2bin(f):
    (d,) = struct.unpack(">Q", struct.pack(">d", f))
    return f'{d:064b}'

def bin2float(b):
    b = b.replace(" ", "")  # Remove spaces if present
    d = int(b, 2)
    packed = struct.pack(">Q", d)
    f = struct.unpack(">d", packed)[0]
    return f

In [19]:
float2bin(10)

'0100000000100100000000000000000000000000000000000000000000000000'

In [26]:
bin2float('0 10000000010 0100000000000000000000000000000000000000000000000000')

10.0